version: '3.8'

services:
  school-bot:
    build: .
    container_name: school-bot
    command: python main.py
    env_file:
      - .env.example
    volumes:
      - ./xlsx_reports:/app/xlsx_reports
    restart: unless-stopped

  school-admin-bot:
    build: .
    container_name: school-admin-bot
    command: python admin_main.py
    env_file:
      - .env.example
    volumes:
      - ./xlsx_reports:/app/xlsx_reports
    restart: unless-stopped

  school-notifyer:
    build: .
    container_name: school-notifyer
    command: supercronic /etc/crontabs/root
    env_file:
      - .env.example
    volumes:
      - ./xlsx_reports:/app/xlsx_reports
    restart: unless-stopped