version: '3.8'

services:
  main_bot:
    build: .
    container_name: main_bot
    command: python main.py
    restart: always
    env_file:
      - .env
    volumes:
      - ./lunch_database.db:/app/lunch_database.db

  admin_bot:
    build: .
    container_name: admin_bot
    command: python admin_main.py
    restart: always
    env_file:
      - .env
    volumes:
      - ./lunch_database.db:/app/lunch_database.db